"""Add consignment and tender models

Revision ID: 56060a3cc05d
Revises: c2fa0551f99c
Create Date: 2025-09-13 01:17:55.648024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56060a3cc05d'
down_revision: Union[str, Sequence[str], None] = 'c2fa0551f99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_contracts',
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('tender_reference', sa.String(length=100), nullable=True),
    sa.Column('tender_winner', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erp_contract_id', sa.String(length=50), nullable=True),
    sa.Column('erp_sync_date', sa.DateTime(), nullable=True),
    sa.Column('contract_document_url', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_contracts_contract_number'), 'tender_contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_tender_contracts_id'), 'tender_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_tender_contracts_public_id'), 'tender_contracts', ['public_id'], unique=True)
    op.create_table('consignment_agreements',
    sa.Column('agreement_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('return_policy_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contract_document_url', sa.String(length=255), nullable=True),
    sa.Column('terms_document_url', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consignment_agreements_agreement_number'), 'consignment_agreements', ['agreement_number'], unique=True)
    op.create_index(op.f('ix_consignment_agreements_id'), 'consignment_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_agreements_public_id'), 'consignment_agreements', ['public_id'], unique=True)
    op.create_table('consignment_statements',
    sa.Column('statement_number', sa.String(length=50), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_shipped_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_sold_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_returned_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount_due', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('statement_document_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('sent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['consignment_agreements.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_number')
    )
    op.create_index(op.f('ix_consignment_statements_id'), 'consignment_statements', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_statements_public_id'), 'consignment_statements', ['public_id'], unique=True)
    op.create_table('consignments',
    sa.Column('consignment_number', sa.String(length=50), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('consignment_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('shipped_by', sa.String(length=50), nullable=True),
    sa.Column('shipped_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['consignment_agreements.id'], ),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id')
    )
    op.create_index(op.f('ix_consignments_consignment_number'), 'consignments', ['consignment_number'], unique=True)
    op.create_index(op.f('ix_consignments_id'), 'consignments', ['id'], unique=False)
    op.create_index(op.f('ix_consignments_public_id'), 'consignments', ['public_id'], unique=True)
    op.create_table('contract_reservations',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['tender_contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id')
    )
    op.create_index(op.f('ix_contract_reservations_id'), 'contract_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_contract_reservations_public_id'), 'contract_reservations', ['public_id'], unique=True)
    op.create_table('consignment_items',
    sa.Column('consignment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consignment_items_id'), 'consignment_items', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_items_public_id'), 'consignment_items', ['public_id'], unique=True)
    op.create_table('consignment_returns',
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('consignment_id', sa.Integer(), nullable=False),
    sa.Column('consignment_item_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('return_reason', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('qc_status', sa.String(length=20), nullable=True),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('qc_by', sa.String(length=50), nullable=True),
    sa.Column('qc_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposition', sa.String(length=50), nullable=True),
    sa.Column('restocked_quantity', sa.Integer(), nullable=False),
    sa.Column('disposed_quantity', sa.Integer(), nullable=False),
    sa.Column('return_document_url', sa.String(length=255), nullable=True),
    sa.Column('photos_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.String(length=50), nullable=True),
    sa.Column('received_by', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ),
    sa.ForeignKeyConstraint(['consignment_item_id'], ['consignment_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_index(op.f('ix_consignment_returns_id'), 'consignment_returns', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_returns_public_id'), 'consignment_returns', ['public_id'], unique=True)
    op.create_table('consignment_sales',
    sa.Column('sale_number', sa.String(length=50), nullable=False),
    sa.Column('consignment_id', sa.Integer(), nullable=False),
    sa.Column('consignment_item_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_customer_name', sa.String(length=100), nullable=True),
    sa.Column('end_customer_info', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_document_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_by', sa.String(length=50), nullable=True),
    sa.Column('reported_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ),
    sa.ForeignKeyConstraint(['consignment_item_id'], ['consignment_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_number')
    )
    op.create_index(op.f('ix_consignment_sales_id'), 'consignment_sales', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_sales_public_id'), 'consignment_sales', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consignment_sales_public_id'), table_name='consignment_sales')
    op.drop_index(op.f('ix_consignment_sales_id'), table_name='consignment_sales')
    op.drop_table('consignment_sales')
    op.drop_index(op.f('ix_consignment_returns_public_id'), table_name='consignment_returns')
    op.drop_index(op.f('ix_consignment_returns_id'), table_name='consignment_returns')
    op.drop_table('consignment_returns')
    op.drop_index(op.f('ix_consignment_items_public_id'), table_name='consignment_items')
    op.drop_index(op.f('ix_consignment_items_id'), table_name='consignment_items')
    op.drop_table('consignment_items')
    op.drop_index(op.f('ix_contract_reservations_public_id'), table_name='contract_reservations')
    op.drop_index(op.f('ix_contract_reservations_id'), table_name='contract_reservations')
    op.drop_table('contract_reservations')
    op.drop_index(op.f('ix_consignments_public_id'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_id'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_consignment_number'), table_name='consignments')
    op.drop_table('consignments')
    op.drop_index(op.f('ix_consignment_statements_public_id'), table_name='consignment_statements')
    op.drop_index(op.f('ix_consignment_statements_id'), table_name='consignment_statements')
    op.drop_table('consignment_statements')
    op.drop_index(op.f('ix_consignment_agreements_public_id'), table_name='consignment_agreements')
    op.drop_index(op.f('ix_consignment_agreements_id'), table_name='consignment_agreements')
    op.drop_index(op.f('ix_consignment_agreements_agreement_number'), table_name='consignment_agreements')
    op.drop_table('consignment_agreements')
    op.drop_index(op.f('ix_tender_contracts_public_id'), table_name='tender_contracts')
    op.drop_index(op.f('ix_tender_contracts_id'), table_name='tender_contracts')
    op.drop_index(op.f('ix_tender_contracts_contract_number'), table_name='tender_contracts')
    op.drop_table('tender_contracts')
    # ### end Alembic commands ###
