"""adding packing manifest

Revision ID: 6c5beb509c8d
Revises: 8f0af58918e5
Create Date: 2025-10-06 02:08:43.822321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c5beb509c8d'
down_revision: Union[str, Sequence[str], None] = '8f0af58918e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packing_manifests',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('tujuan_kirim', sa.String(length=255), nullable=False),
    sa.Column('packing_slip', sa.String(length=50), nullable=True),
    sa.Column('total_boxes', sa.Integer(), nullable=False),
    sa.Column('shipping_address_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_manifests_id'), 'packing_manifests', ['id'], unique=False)
    op.create_index(op.f('ix_packing_manifests_packing_slip'), 'packing_manifests', ['packing_slip'], unique=False)
    op.create_index(op.f('ix_packing_manifests_public_id'), 'packing_manifests', ['public_id'], unique=True)
    op.create_table('packed_boxes',
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('box_number', sa.Integer(), nullable=False),
    sa.Column('sscc', sa.String(length=18), nullable=False),
    sa.Column('gtin', sa.String(length=8), nullable=False),
    sa.Column('petugas', sa.String(length=50), nullable=True),
    sa.Column('berat', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['packing_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packed_boxes_id'), 'packed_boxes', ['id'], unique=False)
    op.create_index(op.f('ix_packed_boxes_public_id'), 'packed_boxes', ['public_id'], unique=True)
    op.create_index(op.f('ix_packed_boxes_sscc'), 'packed_boxes', ['sscc'], unique=True)
    op.create_table('packed_items',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('batch', sa.String(length=50), nullable=False),
    sa.Column('expire_date', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['packed_boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packed_items_id'), 'packed_items', ['id'], unique=False)
    op.create_index(op.f('ix_packed_items_public_id'), 'packed_items', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packed_items_public_id'), table_name='packed_items')
    op.drop_index(op.f('ix_packed_items_id'), table_name='packed_items')
    op.drop_table('packed_items')
    op.drop_index(op.f('ix_packed_boxes_sscc'), table_name='packed_boxes')
    op.drop_index(op.f('ix_packed_boxes_public_id'), table_name='packed_boxes')
    op.drop_index(op.f('ix_packed_boxes_id'), table_name='packed_boxes')
    op.drop_table('packed_boxes')
    op.drop_index(op.f('ix_packing_manifests_public_id'), table_name='packing_manifests')
    op.drop_index(op.f('ix_packing_manifests_packing_slip'), table_name='packing_manifests')
    op.drop_index(op.f('ix_packing_manifests_id'), table_name='packing_manifests')
    op.drop_table('packing_manifests')
    # ### end Alembic commands ###
