"""Add tender_contract_id foreign key to sales_order table

Revision ID: 8586bc846568
Revises: 56060a3cc05d
Create Date: 2025-09-13 02:17:43.481946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8586bc846568'
down_revision: Union[str, Sequence[str], None] = '56060a3cc05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('tender_contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_order', 'tender_contracts', ['tender_contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_order', type_='foreignkey')
    op.drop_column('sales_order', 'tender_contract_id')
    # ### end Alembic commands ###
