"""fixing enum

Revision ID: de94f5e6421f
Revises: 8586bc846568
Create Date: 2025-09-14 01:42:34.618647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de94f5e6421f'
down_revision: Union[str, Sequence[str], None] = '8586bc846568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE allocation_status_enum ADD VALUE 'QUARANTINE'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
